server:
  port: 0

spring:
  application:
    name: sample-proxy-client

logging:
  level:
    org.springframework.messaging.rsocket: INFO
    io.agilehandy.actuator.rsocket.client: DEBUG

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,features,loggers,myloggers
  rsocket:
    client:
      client-name: ${spring.application.name}
      client-id: ${random.int}
      endpoints:
        exposure:
          include: ${management.endpoints.web.exposure.include}
      proxy:
        host: localhost
        port: 7002


