server:
  port: 0

spring:
  application:
    name: sample-proxy-client

logging:
  level:
    org.springframework.messaging.rsocket: INFO
    io.agilehandy.actuator.rsocket.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,features
  rsocket:
    client:
      client-name: ${spring.application.name}
      client-id: 1
      endpoints:
        exposure:
          include: ${management.endpoints.web.exposure.include}
      proxy:
        host: localhost
        port: 7002

---
spring:
  profiles: second

management:
  rsocket:
    client:
      client-id: 2

---
spring:
  profiles: third

management:
  rsocket:
    client:
      client-id: 3

---
spring:
  profiles: forth

management:
  rsocket:
    client:
      client-id: 4

